### ISSUE TITLE
Version for 1.7.10 says it's for 1.8.9 in mod options menu

### ISSUE THREAD

**Issue by dirtyfargo** [VapourDrive/Alt-F4#3]
Not really an issue, just figured you might want to know :P 
https://gyazo.com/b373390f569e18962d5bbdfca271e39b

**Comment by ColinGBos** [comment]
yeah, that doesn't change anything really. Not sure why I have a broken mcmod.info file; I'll look into it, thanks.

**Comment by dirtyfargo** [comment]
no problem :)

**Comment by ColinGBos** [comment]
Fixed, pushing new build.
