### ISSUE TITLE
Thaumcraft smelting issues

### ISSUE THREAD

**Issue by Woif1990** [VapourDrive/Alt-F4#4]
Well while my crashing issues are gone, I found another issue. Unsure if I should report it to you or Azanor but two things:
When you try and smelt a native cluster, it should smelt into two ingots. It smelts into one with your furnaces.
Secondly, if you try and put two different types of clusters in, the second ones put in will turn into the first type. i.e. put in a gold native cluster first, then an iron one, you end up with two gold clusters.

**Comment by ColinGBos** [comment]
Thanks for the report, it's likely on my end, so I'll definitely have a look before you report to azanor (anything that works in the vanilla furnace but not in mine is probably on my end)

**Comment by Woif1990** [comment]
Oh, also the % when smelting Clusters will go to 200% complete with the bar going past the arrow.

**Comment by ColinGBos** [comment]
Wow these clusters are really throwing my furnace for a loop huh, having a look at these, I see why the stacks are joining, fixing that now.

**Comment by ColinGBos** [comment]
Well, the stack size issue is actually a forge bug, not mine, but I can work around it. And I'll submit an issue to them about it. I have fixed the issue with the stacks merging when they weren't supposed to. I don't however have the issue with the arrow growing too large...
![2016-01-14_20 20 42](https://cloud.githubusercontent.com/assets/5392006/12342847/60e97f6a-bafc-11e5-8e6d-a543a96aa2e3.png)

**Comment by Woif1990** [comment]
Well glad that's all taken care of!
As for the arrow, probably just weird cross mod stuff. Won't affect much anyways.

**Comment by ColinGBos** [comment]
Fixed in latest commit
