### ISSUE TITLE
Automation Troubles

### ISSUE THREAD

**Issue by Candyman711** [VapourDrive/Alt-F4#5]
Top slot of furnace not available for input

**Comment by ColinGBos** [comment]
Sorry, read this and then forgot about it, what version is this on?

**Comment by Candyman711** [comment]
No Problem, Version: Alt-F4-1.8.9-0.0.2.7

**Comment by ColinGBos** [comment]
I tested and I can fully automate it.
Hoppers above will input into the input slots _if_ the item has a valid recipe.
Hoppers to the side will take a stack and try to put it into the input _if_ it has a valid recipe, but will try to put it into the fuel slot _if_ it is a registered fuel.
Make sure the stack you are trying to put in via automation is actually a valid input.
I will reopen this if you can still show that it doesn't work with a scenario or screenshots.

**Comment by Candyman711** [comment]
Seems to only be a issue if the Item you want to smelt is a fuel. ex.Logs 
![2016-01-23_16 21 07](https://cloud.githubusercontent.com/assets/16723555/12533482/8febc71c-c1ed-11e5-82c4-f52def709fff.png)

**Comment by ColinGBos** [comment]
Ah OK, that makes sense, thanks for the elaboration. I'll work on a fixand push a new build asap.
