### ISSUE TITLE
NEI useage button has major lag and crashes in multiplayer

### ISSUE THREAD

**Issue by dirtyfargo** [VapourDrive/Alt-F4#6]
When I have this mod installed alongside NEI, NEI's useage button is extremely laggy, taking about 48 seconds to work. Also, on a server, just clicking any recipe in NEI crashes the client with no crash report as well as using the useage button. 
Version: 0.0.2.9
Forge Version: 1.7.10-10.13.4.1614
NEI: 1.0.5.120
Code Chicken Core: 1.0.7.47
When I remove Alt-F4 the problem is fixed.
Thanks =)

**Comment by Skillotic0703** [comment]
I can confirm

**Comment by ColinGBos** [comment]
Yeah it's laggy in the 1.7.10 version but I'm considering that EoL Sorry :(
