### ISSUE TITLE
Experience Crystal has no way to use?

### ISSUE THREAD

**Issue by PlasmaNoodle** [VapourDrive/Alt-F4#7]
Does the experience crystal even work? If it does can i be told how it works or if it is a bug?

**Comment by ColinGBos** [comment]
It does work, what part are you struggling to figure out? Though I should show in the Curse Page more information on it's actual use. You can charge it with experience in the furnace, in the top slot, as long as there is more than 10XP, it will fill the crystal. Then just context click with it in your hand and you will get the experience out of it.
